#EXTM3U
#PLAYLIST:Generated by CODECS.COM Playlist Builder

#EXTINF:-1 group-title="-",HBO HD
http://190.115.3.141:9000/play/a0wo/index.m3u8

#EXTINF:-1 group-title="-",HBO Family HD
http://190.115.3.141:9000/play/a0wn/index.m3u8

#EXTINF:-1 group-title="-",HBO XTREME
http://190.115.3.141:9000/play/a0mu/index.m3u8

#EXTINF:-1 group-title="-",HBO Plus HD
http://190.115.3.141:9000/play/a0wp/index.m3u8

#EXTINF:-1 group-title="-",HBO2 HD
http://190.115.3.141:9000/play/a0qj/index.m3u8
